### ISSUE TITLE
Incomplete details

### ISSUE THREAD

**Issue by KamilKluba** [Sxtanna/dependency-loader#11]
After i add dependency to config.yml and run a server i get:

> =============================================
> [21:44:14] [Server thread/ERROR]: [DLoader] <
> [21:44:14] [Server thread/ERROR]: [DLoader] < Dependency commons-io has incomplete details
> [21:44:14] [Server thread/ERROR]: [DLoader] < Requires, case-sensitive
> [21:44:14] [Server thread/ERROR]: [DLoader] < 'version', 'group', 'artifact'
> [21:44:14] [Server thread/ERROR]: [DLoader] =============================================

In config.yml i have:
```
dependencies:
    commons-io:
        version:2.6
        group:commons-io
        artifact:commons-io
        repository:http://central.maven.org/maven2/
```

Can you help me?

**Comment by Sxtanna** [comment]
Your YML is invalid.

Use this:
```yaml
dependencies:
  commons-io:
    version: 2.6
    group: 'commons-io'
    artifact: 'commons-io'
    repository: 'http://central.maven.org/maven2/'
```
